### ISSUE TITLE
Ontology TODO

### ISSUE THREAD

**Issue by ktk** [zazuko/swiss-performing-arts#5]
- [ ] `subClassOf`: use ontology row
- [x] `equivilentClass`: Split by pipe & generate triples
- [ ] Replace`|`with newlines in text blocks
- [ ] cleanup `superClassOf`, see issue #4
- [ ] Kick out literals with just a whitespace or `-`
